const buttonFilled = {
  white: {
    background: "bg-white",
    color: "text-neutral-700",
    shadow: "shadow-md shadow-neutral-500/20",
    hover: "hover:shadow-lg hover:shadow-neutral-500/30",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  blue: {
    background: "bg-blue-500",
    color: "text-white",
    shadow: "shadow-md shadow-blue-500/30",
    hover: "hover:shadow-lg hover:shadow-blue-500/40",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  dark: {
    background: "bg-neutral-800",
    color: "text-white",
    shadow: "shadow-md shadow-neutral-500/50",
    hover: "hover:shadow-lg hover:shadow-neutral-500/60",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  gray: {
    background: "bg-gray-400",
    color: "text-white",
    shadow: "shadow-md shadow-gray-500/50",
    hover: "hover:shadow-lg hover:shadow-gray-500/60",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  green: {
    background: "bg-green-500",
    color: "text-white",
    shadow: "shadow-md shadow-green-500/50",
    hover: "hover:shadow-lg hover:shadow-green-500/60",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  pink: {
    background: "bg-pink-500",
    color: "text-white",
    shadow: "shadow-md shadow-pink-500/50",
    hover: "hover:shadow-lg hover:shadow-pink-500/60",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  purple: {
    background: "bg-purple-500",
    color: "text-white",
    shadow: "shadow-md shadow-purple-500/50",
    hover: "hover:shadow-lg hover:shadow-purple-500/60",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  red: {
    background: "bg-red-500",
    color: "text-white",
    shadow: "shadow-md shadow-red-500/50",
    hover: "hover:shadow-lg hover:shadow-red-500/60",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  yellow: {
    background: "bg-yellow-500",
    color: "text-white",
    shadow: "shadow-md shadow-yellow-500/50",
    hover: "hover:shadow-lg hover:shadow-yellow-500/60",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
};

export default buttonFilled;
